version: '3.8'
services:
    mongo:
        image: mongo:4.4.11-rc1
        ports:
            - 27017:27017
    zookeeper:
        image: bitnami/zookeeper:3.7
        ports:
            - 2181:2181
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
    kafka:
        image: bitnami/kafka:3.0.0
        ports:
            - 9092:9092
            - 9093:9093
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
            - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
            - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
            - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        healthcheck:
          test: [ 'CMD-SHELL', './opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9093 --list' ]
          interval: 10s
          timeout: 60s
          retries: 6
    backend:
        build: backend
        depends_on:
            kafka:
                condition: service_healthy
        ports:
            - 8000:8000
    distribution_manager:
        build: distribution_manager
        depends_on:
            kafka:
                condition: service_healthy
        ports:
            - 8888:8888